version: "3"
services:
  auth-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=doctest
      - POSTGRES_USER=doctest_user
      - POSTGRES_PASSWORD=doctest_password
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    restart: always
  authorization:
    image: auth-server-image
    build:
      context: /authorization-service
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db/doctest
      - AUTHCLIENT_URL=hashtranslator
    depends_on:
      - auth-db
    ports:
      - "9000:9000"
  hash-db:
    image: mongo:7
    volumes:
      - hash-db-data:/data/db
    restart: always
  hashtranslator:
    image: hashtranslator-image
    build:
      context: /hashtranslator-service
      dockerfile: Dockerfile
    environment:
      - AUTHSERVER_URL=http://127.0.0.1:9000
      - SPRING_DATA_MONGODB_URI=mongodb://hash-db:27017/hashtest
    depends_on:
      - hash-db
    ports:
      - "8080:8080"
volumes:
  auth-db-data:
  hash-db-data: